// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace WpfApp6.Models;

[PrimaryKey("TryIp", "DateofTry")]
[Table("tblLoginTry")]
public partial class TblLoginTry
{
    [Key]
    [Column("TryIP")]
    [StringLength(16)]
    [Unicode(false)]
    public string TryIp { get; set; }

    [Key]
    [Column(TypeName = "datetime")]
    public DateTime DateofTry { get; set; }
}