// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace WpfApp6.Models;

[Table("tblTreatment")]
public partial class TblTreatment
{
    [Key]
    public int TreatmentId { get; set; }

    public int PrescriptionDoctorUserId { get; set; }

    public int PatientUserId { get; set; }

    public int DiseaseId { get; set; }

    [ForeignKey("TreatmentId")]
    [InverseProperty("Treatment")]
    public virtual ICollection<TblDrugs> Drug { get; set; } = new List<TblDrugs>();
}