// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace WpfApp6.Models;

[Table("tblUserType")]
public partial class TblUserType
{
    [Key]
    public byte UserTypeId { get; set; }

    [Required]
    [StringLength(156)]
    public string UserTypeName { get; set; }

    [InverseProperty("UserTypeNavigation")]
    public virtual ICollection<TblUser> TblUser { get; set; } = new List<TblUser>();
}